### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by mreinstein**
* whistlerr can now work in both node and browser
* can have more than one whistlerr instance running at once

### CODE REVIEW

**Comment by shubhamjain** [comment]
Thanks a lot for these changes. Is  the node based detector working good? In my case, it didn't really work.

**Comment by mreinstein** [comment]
> Is the node based detector working good?

It *seems* to be working. See attached screen shot.

>  In my case, it didn't really work.

I'm wondering, what happened? Did it not detect any whistling?




screen shot 2017-02-07 at 9 06 33 am

**Comment by mreinstein** [comment]
I'm wondering if any problems you're experiencing with the detector code are due to configuration values set here: https://github.com/mreinstein/whistlerr/blob/master/demo/node/index.js#L16-L33

maybe tweaking these would make it start detecting for you.

**Comment by shubhamjain** [comment]
I don't know what happened but working well now. Although, I think the lesser noise could've made the difference.

Anyways, I would glad to accept this pull request. Thanks a lot for this! I didn't knew it could be done so easily in node.js.

**Comment by mreinstein** [comment]
I just added you as a collaborator on https://www.npmjs.com/package/whistlerr

feel free to publish the first version! :)

**Comment by mreinstein** [comment]
also feel free to remove me as a collaborator if you'd like to be the sole maintainer. I just reserved the name so noone else would take it from you.

**Comment by shubhamjain** [comment]
Thank you Mike! I'd be glad to have it stay. :)

**Pull request merged**
